#!/bin/bash
cd ..
javac -sourcepath . backupbuddies/Main.java
#java -cp . backupbuddies.Main
mkdir META-INF
cp backupbuddies/MANIFEST.MF META-INF
zip -r bub.zip META-INF backupbuddies
mv bub.zip BackupBuddies.jar
java -jar BackupBuddies.jar
