#!/bin/bash
javac -sourcepath .. Main.java
#java -cp .. backupbuddies.Main
jar -cfm BackupBuddies.jar manifest.mf ./*.class ./cli/*.class ./gui/*.class ./network/*.class ./network/packet/*.class ./shared/*.class
java -jar BackupBuddies.jar
