#!/bin/bash
cd ..
javac -sourcepath . backupbuddies/Main.java
#java -cp . backupbuddies.Main
mkdir META-INF
cp backupbuddies/MANIFEST.MF META-INF
zip -r bub.zip META-INF backupbuddies >build.log
mv bub.zip BackupBuddies.jar
rm ./backupbuddies/*.class ./backupbuddies/*cli/*.class ./backupbuddies/*gui/*.class ./backupbuddies/*shared/*.class ./backupbuddies/*network/*.class ./backupbuddies/*network/packet/*.class 
rm -r META-INF
java -jar BackupBuddies.jar testUnits
